{
 "title": "ShoppingCartApp KPIs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Client Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(akka_actor_activeSessions{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"})"
    }
   ]
  },
  {
   "title": "Successful Session Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(irate(akka_actor_successfulSessions{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"}[1m]))"
    }
   ]
  },
  {
   "title": "Failed Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (stage, reason) (irate(akka_actor_failedSessions{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"}[1m]))"
    }
   ]
  },
  { "title": "Server KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Shopping Carts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, instance)(akka_actor_running_actors{actor=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCart\"})"
    }
   ]
  },
  {
   "title": "Cart Commit Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(irate(akka_actor_cartsCommitted{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"}[1m]))"
    }
   ]
  },
  {
   "title": "Carts Out of Date Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(irate(akka_actor_cartsOutOfDate{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"}[1m]))"
    }
   ]
  },
  {
   "title": "Products Added Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, instance)(irate(akka_actor_productsAdded{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"}[1m]))"
    }
   ]
  },
  {
   "title": "Http 2xx Response Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(quantile)(akka_http_http_server_response_time_2xx_ns{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"} / 1000000)"
    }
   ]
  },
  {
   "title": "Http 2xx Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_http_http_server_responses_2xx{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"}[1m]))"
    }
   ]
  },
  {
   "title": "Http 4xx Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_http_http_server_responses_4xx{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"}[1m]))"
    }
   ]
  },
  {
   "title": "Http 5xx Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_http_http_server_responses_4xx{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"}[1m]))"
    }
   ]
  },
  { "title": "Akka Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Shards per Region",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(shard_region_shard_count_value{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"})"
    }
   ]
  },
  {
   "title": "Phi Accrual Value",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (kubernetes_pod_name, self_node, remote_node)(remote_node_phi_accrual_value{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"})"
    },
    {
     "expr": "min (self_node_phi_accrual_threshold_value)"
    }
   ]
  },
  {
   "title": "Node Reachability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " max by (kubernetes_pod_name,instance)(self_node_reachable_nodes{application=\"com.lightbend.esdemos.shoppingcartapp.ShoppingCartApp\"})"
    }
   ]
  }
 ]
}